version: '3.9'
services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: viralvault
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: viralvault
    depends_on:
      - db
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    ports:
      - "3000:3000"

volumes:
  db-data: